/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MovieListRouteRouteImport } from './routes/MovieListRoute'
import { Route as AuthRouteRouteImport } from './routes/AuthRoute'
import { Route as IndexRouteImport } from './routes/index'

const MovieListRouteRoute = MovieListRouteRouteImport.update({
  id: '/MovieListRoute',
  path: '/MovieListRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/AuthRoute',
  path: '/AuthRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AuthRoute': typeof AuthRouteRoute
  '/MovieListRoute': typeof MovieListRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AuthRoute': typeof AuthRouteRoute
  '/MovieListRoute': typeof MovieListRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AuthRoute': typeof AuthRouteRoute
  '/MovieListRoute': typeof MovieListRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/AuthRoute' | '/MovieListRoute'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/AuthRoute' | '/MovieListRoute'
  id: '__root__' | '/' | '/AuthRoute' | '/MovieListRoute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRoute
  MovieListRouteRoute: typeof MovieListRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/MovieListRoute': {
      id: '/MovieListRoute'
      path: '/MovieListRoute'
      fullPath: '/MovieListRoute'
      preLoaderRoute: typeof MovieListRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AuthRoute': {
      id: '/AuthRoute'
      path: '/AuthRoute'
      fullPath: '/AuthRoute'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRoute,
  MovieListRouteRoute: MovieListRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
