/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MovieListRouteImport } from './routes/movieList'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserSearchRouteImport } from './routes/user/search'
import { Route as UserPersonalRouteImport } from './routes/user/personal'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const MovieListRoute = MovieListRouteImport.update({
  id: '/movieList',
  path: '/movieList',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSearchRoute = UserSearchRouteImport.update({
  id: '/user/search',
  path: '/user/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPersonalRoute = UserPersonalRouteImport.update({
  id: '/user/personal',
  path: '/user/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movieList': typeof MovieListRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/user/personal': typeof UserPersonalRoute
  '/user/search': typeof UserSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movieList': typeof MovieListRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/user/personal': typeof UserPersonalRoute
  '/user/search': typeof UserSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movieList': typeof MovieListRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/user/personal': typeof UserPersonalRoute
  '/user/search': typeof UserSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movieList'
    | '/auth/login'
    | '/auth/register'
    | '/user/personal'
    | '/user/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movieList'
    | '/auth/login'
    | '/auth/register'
    | '/user/personal'
    | '/user/search'
  id:
    | '__root__'
    | '/'
    | '/movieList'
    | '/auth/login'
    | '/auth/register'
    | '/user/personal'
    | '/user/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieListRoute: typeof MovieListRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  UserPersonalRoute: typeof UserPersonalRoute
  UserSearchRoute: typeof UserSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/movieList': {
      id: '/movieList'
      path: '/movieList'
      fullPath: '/movieList'
      preLoaderRoute: typeof MovieListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/search': {
      id: '/user/search'
      path: '/user/search'
      fullPath: '/user/search'
      preLoaderRoute: typeof UserSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/personal': {
      id: '/user/personal'
      path: '/user/personal'
      fullPath: '/user/personal'
      preLoaderRoute: typeof UserPersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieListRoute: MovieListRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  UserPersonalRoute: UserPersonalRoute,
  UserSearchRoute: UserSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
